//
//  HistoryModels.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 16/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum History {
  // MARK: Use cases
        
    enum FetchFundsID {
        struct Request {
 
        }
        struct Response {
            var fcode: String
            var portNo: Int
        }
        struct ViewModel {
            var fcode: String
            var portNo: Int
        }
    }
    enum FetchHistoryData   {
        struct Request  {
            var username: String
            var portno: Int
            var fcode: String
        }
        struct Response   {
            var getHistory: GetHistoryModel?
            var error: Error?
        }
        struct ViewModel  {
            var getHistory: GetHistoryModel?
            var error: Error?
        }
    }
}

