//
//  HistoryPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 16/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryPresentationLogic
{
    func presentFundscode(response: History.FetchFundsID.Response)
    func presentfetchHistory(response: History.FetchHistoryData.Response)
}

class HistoryPresenter: HistoryPresentationLogic
{
  weak var viewController: HistoryDisplayLogic?
  
  // MARK: Do something
  
    func presentfetchHistory(response: History.FetchHistoryData.Response)
    {
      let viewModel = History.FetchHistoryData.ViewModel(getHistory: response.getHistory, error: response.error)
      viewController?.displayfetchHistory(viewModel: viewModel)
    }
    func presentFundscode(response: History.FetchFundsID.Response) {
        let viewModel = History.FetchFundsID.ViewModel(fcode: response.fcode, portNo: response.portNo)
        viewController?.displayfetchfundscode(viewModel: viewModel)
    }
}
