//
//  BuyAndSaleInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 15/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyAndSaleBusinessLogic
{
    func doFetchData(request: BuyAndSale.FetchData.Request)
}

protocol BuyAndSaleDataStore
{
    var fundsList:[ReealmFundsListMobile]? {get set}
    var portNo: Int? {get set}
    var getOrderList: DataGetOrder? {get set}
}

class BuyAndSaleInteractor: BuyAndSaleBusinessLogic, BuyAndSaleDataStore
{
  var presenter: BuyAndSalePresentationLogic?
  var worker: BuyAndSaleWorker?
    var fundsList: [ReealmFundsListMobile]?
    var portNo: Int?
    var getOrderList: DataGetOrder?
  // MARK: Do something
    func doFetchData(request: BuyAndSale.FetchData.Request)
    {
      worker = BuyAndSaleWorker()
      worker?.doSomeWork()
//        print("fcode", getOrderList)
      let response = BuyAndSale.FetchData.Response(fundsList: fundsList, portNo: portNo, getOrderList: getOrderList)
      presenter?.presentFetchData(response: response)
    }
}
