//
//  BuyAndSaleModels.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 15/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BuyAndSale
{
  // MARK: Use cases
  
    enum FetchData {
      struct Request {
      }
      struct Response {
          var fundsList: [ReealmFundsListMobile]?
          var portNo: Int?
          var getOrderList: DataGetOrder?
      }
      struct ViewModel {
          var fundsList: [ReealmFundsListMobile]?
          var portNo: Int?
          var getOrderList: DataGetOrder?
      }
    }
}
