//
//  BuyAndSalePresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 15/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyAndSalePresentationLogic
{
    func presentFetchData(response: BuyAndSale.FetchData.Response)
}

class BuyAndSalePresenter: BuyAndSalePresentationLogic
{
  weak var viewController: BuyAndSaleDisplayLogic?
  
  // MARK: Do something
  
    func presentFetchData(response: BuyAndSale.FetchData.Response)
    {
      let viewModel = BuyAndSale.FetchData.ViewModel(fundsList: response.fundsList, portNo: response.portNo, getOrderList: response.getOrderList)
      viewController?.displayFetchData(viewModel: viewModel)
    }
}
