//
//  PortDetailWorker.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 25/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON
class PortDetailWorker
{
    typealias FecthDeleteDataDataCompletionHandler = (_ deleteData: DeleteModel?,_ error: Error?) -> ()
    func fecthDelteData(delFlag: String, username: String, portNo: Int, channel: String, completionHandler: @escaping FecthDeleteDataDataCompletionHandler) {
        let router = Funds.deleteOrder.path
        Alamofire.request(router, method: .post, parameters: ["DelFlag": delFlag, "username": username, "portno": portNo, "channel": channel]).responseJSON { response in
            if response.error != nil {
                completionHandler(nil, response.error)
                return
            }
            
            if let data = response.data {
                print("data>>", response.value)
                do {
                    let deleteDataModel = try JSONDecoder().decode(DeleteModel.self, from: data)
                 //   print("getOrderModelData >> ", deleteDataModel)
                    completionHandler(deleteDataModel, nil)
                    
                } catch let error {
                    print("Failed to load: \(error.localizedDescription)")

                    completionHandler(nil, error)
                }
            }
        }
    }
    typealias FecthGetOrderDataCompletionHandler = (_ getOrderData: GetOrderModel?,_ error: Error?) -> ()
    func fecthGetOrderData(username: String, portNo: Int,completionHandler: @escaping FecthGetOrderDataCompletionHandler) {
        let router = Funds.getOder.path
//        print("\(router)username=\(username)&portNo=\(portNo)")
//        let url = URL(string: "\(router)username=\(username)&portNo=\(portNo)" )!
//        var request = URLRequest(url: url)
//        request.httpMethod = "POST"
        Alamofire.request(router, method: .post, parameters: ["username": username, "portNo": portNo]).responseJSON { response in
            if response.error != nil {
                completionHandler(nil, response.error)
                return
            }
            
            if let data = response.data {
                do {
                    let getOrderModelData = try JSONDecoder().decode(GetOrderModel.self, from: data)
//                    print("getOrderModelData >> ", getOrderModelData)
                    completionHandler(getOrderModelData, nil)
                    
                } catch let error {
                    print("Failed to load: \(error.localizedDescription)")

                    completionHandler(nil, error)
                }
            }
        }
    }
}
