//
//  FundsIPOInteractor.swift
//  QuizFundsIPO
//
//  Created by BUSSNQ TH on 25/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundsIPOBusinessLogic
{
  func setupFetchFromLocalDataStore(request: FundsIPO.FetchFromLocalDataStore.Request)
    func setupFetchFundsData(request: FundsIPO.FetchFundsDatas.Requests)
}

protocol FundsIPODataStore
{
  var fundsIPO: FundIPORolloverDataModels? { get set }
    var fundsData : [ModelFunds]? { get set }
}

class FundsIPOInteractor: FundsIPOBusinessLogic, FundsIPODataStore {
    var fundsData: [ModelFunds]?
    
    var fundsIPO: FundIPORolloverDataModels?
    typealias Models = FundsIPO
  var presenter: FundsIPOPresentationLogic?
  var worker: FundsIPOWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func setupFetchFromLocalDataStore(request: FundsIPO.FetchFromLocalDataStore.Request)
  {
    worker = FundsIPOWorker()
    worker?.doSomeWork()
    
    let response = FundsIPO.FetchFromLocalDataStore.Response(iPOData: fundsIPO)
    presenter?.presentSomething(response: response)
  }
    func setupFetchFundsData(request: FundsIPO.FetchFundsDatas.Requests) {
        worker = FundsIPOWorker()
        let nameFunds = request.nameFunds
//        print(nameFunds)
        worker?.doFetchFunds(nameFund: nameFunds) { (fundsData, error) in
            if error != nil {
                let response = Models.FetchFundsDatas.Response(fundsData: nil, error: error)
                self.presenter?.presentFunds(response: response)
                return
            }
            
            let response = Models.FetchFundsDatas.Response(fundsData: fundsData, error: nil)
          
            self.presenter?.presentFunds(response: response)
        }
        
    }
    
}
