//
//  FundsIPOModels.swift
//  QuizFundsIPO
//
//  Created by BUSSNQ TH on 25/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FundsIPO {
  // MARK: Use cases
  
    enum FetchFromLocalDataStore {
        struct Request {
        }

        struct Response {
            var iPOData: FundIPORolloverDataModels?
        }

        struct ViewModel {
            var iPOData: FundIPORolloverDataModels?
        }
    }
    enum FetchFundsDatas {
        struct Requests {
            var nameFunds: String
        }

        struct Response {
            var fundsData: [ModelFunds]?
            var error: Error?
        }

        struct ViewModel {
            var fundsData: [ModelFunds]?
            var error: Error?
        }
        
    }
}
