//
//  FundsIPOWorker.swift
//  QuizFundsIPO
//
//  Created by BUSSNQ TH on 25/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
class FundsIPOWorker {
  func doSomeWork() {
  }
    typealias Models = FundsIPO

    typealias FecthFundsDataCompletionHandler = (_ fundsData: [ModelFunds]?,_ error: Error?) -> ()
    func doFetchFunds(nameFund: String,  completionHandler: @escaping FecthFundsDataCompletionHandler) {
        AF.request("https://www.fame.in.th/FAMEMvc/api/DashUnAuthor/\(nameFund)", method:.post,encoding:    JSONEncoding.default).response { response in
            if response.error != nil {
                completionHandler(nil, response.error)
                return
            }
            
            if let data = response.data {
                do {
                    let fundsModelData = try JSONDecoder().decode([ModelFunds].self, from: data)
//                    print("iPOModelData>>", iPOModelData)
                    completionHandler(fundsModelData, nil)
                    
                } catch let error {
                    completionHandler(nil, error)
               
                }
            }
        }
    }
}
