# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'IPOandRollover' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IPOandRollover
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'LanguageManager-iOS'
  pod 'SDWebImage'
end
