//
//  FundSaleModels.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 15/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FundSale
{
  // MARK: Use cases
  
  enum FetchData {
    struct Request {
    }
    struct Response {
        var risk : Int
        var fcode: String
        var mainPage: String
        var enName: String
        var thName: String
        var nav: String
        var chage: String
        var color: String
        var buy: String
        var sell: String
        var datenav: String
        var portNo: Int?
        var assetCompany: String
        var investOpenDate: String
        var getOrderList: DataGetOrder?
    }
    struct ViewModel {
        var risk : Int
        var fcode: String
        var mainPage: String
        var enName: String
        var thName: String
        var nav: String
        var chage: String
        var color: String
        var buy: String
        var sell: String
        var datenav: String
        var portNo: Int?
        var assetCompany: String
        var investOpenDate: String
        var getOrderList: DataGetOrder?
    }
  }
    enum  FetchInsertDataFunds {
      struct Request {
          var username: String
          var portNo: Int
          var portName: String
          var fcode: String
          var ordtp: Double
          var grsam: Double
          var units: Double
          var unprc: Double
          var trndt: String
          var status: String
          var channel:String
          var realized: String
      }
      struct Response {
          var insertOrder: InsertOrderModel?
         
          var error: Error?
      }
      struct ViewModel {
          var insertOrder: InsertOrderModel?
        
          var error: Error?
      }
    }
}
