//
//  FundSaleRouter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 15/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundSaleRoutingLogic
{
    func sendDatagoToRiskPreview(risk: Int?)
    func backtoMainPagePreview()
    func backtoPagePreview()
    func goToSimportPage() 
}

protocol FundSaleDataPassing
{
  var dataStore: FundSaleDataStore? { get }
}

class FundSaleRouter: NSObject, FundSaleRoutingLogic, FundSaleDataPassing
{
  weak var viewController: FundSaleViewController?
  var dataStore: FundSaleDataStore?
  
  // MARK: Routing
  
    func sendDatagoToRiskPreview(risk: Int?) {
         let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "RiskViewController") as! RiskViewController
         var destinationDS = destinationVC.router!.dataStore!
        destinationDS.risk = risk
        viewController?.present(destinationVC, animated: true)
        
    }
    func backtoMainPagePreview() {
//        let destinationtabbarVC = UITapbar.performSegue(withIdentifier: "tabBar", sender: self
       
        viewController?.view.window?.rootViewController?.dismiss(animated: false, completion: nil)
        
    }
    func backtoPagePreview() {
        viewController?.dismiss(animated: true, completion: nil)
    }
    func goToSimportPage() {
        let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SimulationportViewController") as! SimulationportViewController
       viewController?.present(destinationVC, animated: true)
    }
}
