//
//  FundSaleWorker.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 15/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON
class FundSaleWorker
{
    typealias FecthInsertDataCompletionHandler = (_ getHistory: InsertOrderModel?,_ error: Error?) -> ()
    func fecthInsertData(username: String, portNo: Int, portName: String, fcode: String, ordtp: Double, grsam: Double, units: Double, unprc: Double, trndt: String, status: String, channel:String, realized: String, completionHandler: @escaping FecthInsertDataCompletionHandler) {
        let router = Funds.insertOrder.path
        Alamofire.request(router, method: .post, parameters: ["username": username, "portNo": portNo, "portName": portName, "fcode": fcode, "ordtp": ordtp, "grsam": grsam, "units": units, "unprc": unprc, "trndt": trndt, "status": status, "channel":channel, "realized": realized]).responseJSON { response in
            if response.error != nil {
                completionHandler(nil, response.error)
                return
            }
            
            if let data = response.data {
                print("data>>", response.value)
                do {
                    let insertOrderModel = try JSONDecoder().decode(InsertOrderModel.self, from: data)
//                    print("getOrderModelData >> ", getOrderModelData)
                    completionHandler(insertOrderModel, nil)
                    
                } catch let error {
                    print("Failed to load: \(error.localizedDescription)")

                    completionHandler(nil, error)
                }
            }
        }
    }
}
