//
//  IPORolloverInteractor.swift
//  IPOandRollover
//
//  Created by BUSSNQ TH on 21/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IPORolloverBusinessLogic
{
  func doFetchIPORollover(request: IPORolloverModel.FetchIPORollover.Request)
}

protocol IPORolloverDataStore
{
  //var name: String { get set }
}

class IPORolloverInteractor: IPORolloverBusinessLogic, IPORolloverDataStore {
    
    var presenter: IPORolloverPresentationLogic?
      var worker: IPORolloverWorker?

    func doFetchIPORollover(request: IPORolloverModel.FetchIPORollover.Request) {
        
       
    }
    
  
//    var ipos = worker?.fetchIPOs()
  
  func doFetchIPORollover() {
    let requestWorker = IPORolloverWorker().fetchIPORollover
  
    presenter?.FetchIPORollover(ipoRolloverData: requestWorker)
  }
//    let response = IPORolloverModel.FetchIPORollover.Response(ipoRolloverData: IPORolloverData)
//
  }

