//
//  IPORolloverWorker.swift
//  IPOandRollover
//
//  Created by BUSSNQ TH on 21/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON
protocol IPOFetchType {
    func fetchIPOs()
}
class IPORolloverWorker {
    var fetchIPORollover: [IPORolloverData] = []
    func fetchIPOs() {
    let url = "https://www.fame.in.th/FAMEMvc/api/DashUnAuthor/IPO"
        AF.request(url, method:.post,encoding: JSONDecoder.self as! ParameterEncoding) .responseJSON { (response) ->  Void in
        switch response.result {
        case .success:
            print("Successful")
              //  print("Data ", response.value)
                    do {
                        let dataJSON = JSON(response.value ?? "")
                        let fundipo = dataJSON

                        let fundiporolloverData = try fundipo.rawData(options: .fragmentsAllowed)
                        let fundiporolloveModel = try JSONDecoder().decode([IPORolloverData].self, from: fundiporolloverData)
//                        print(fundiporolloveModel)
                        self.fetchIPORollover = fundiporolloveModel
                        print("Data>>>", self.fetchIPORollover)
                    }
                    catch let err{
                        print("Err", err)
                        
                    }
                case let .failure(error):
                    print(error)
                    
                }
               }
  }
}
