//
//  IPORolloverWorker.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 28/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON
class IPORolloverWorker {
    
    typealias Models = IPORollovers
    typealias FecthFundsIPODataCompletionHandler = (_ fundsIPOData: [FundIPORolloverDataModels]?,_ error: Error?) -> ()
    func fetchFundsIPOData(nameFund: String,  completionHandler: @escaping FecthFundsIPODataCompletionHandler) {
        
        AF.request("https://www.fame.in.th/FAMEMvc/api/DashUnAuthor/\(nameFund)", method:.post,encoding:    JSONEncoding.default).response { response in
            
            if response.error != nil {
                completionHandler(nil, response.error)
                return
            }
            
            if let data = response.data {
                do {
                    let iPOModelData = try JSONDecoder().decode([FundIPORolloverDataModels].self, from: data)
//                    print("iPOModelData>>", iPOModelData)
                    completionHandler(iPOModelData, nil)
                    
                } catch let error {
                    completionHandler(nil, error)
               
                }
            }
        }
    }
//    typealias FecthFundsIPODatasCompletionHandler = (_ fundsIPOData: [TestModel]?,_ error: Error?) -> ()
    func fetchFundsIPODatas() {
        let router = Funds.asURLRequest(Funds.iPO)

        print(router())
        AF.request(router()).responseJSON { (response) in
            print(response.value)
            switch response.result {
                  case .success(let value):
                      print(value)
                  case .failure(let error):
                      print(error)
                  }
//            if response.error != nil {
////                completionHandler(nil, response.error)
//                print(Error.self)
//                return
//            }
//            if let data = response.value {
//                do {
//                    let dataJSON = JSON(data)
////                    let fundAnalystTalk = dataJSON["AnalystTalk"]
//                    let fundAnalystTalkData = try dataJSON.rawData(options: .fragmentsAllowed)
//                    let analystTalksData = try JSONDecoder().decode([FundIPORolloverDatasModels].self, from: fundAnalystTalkData)
//                    print("FundsanalystReport", analystTalksData)
////                    completionHandler(analystTalksData, nil)
//                } catch let error {
////                    completionHandler(nil, error)
//                    print(error)
//                }
//            }
        }
}
}
