//
//  IPORolloverWorker.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 28/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON
class IPORolloverWorker {
    
    typealias Models = IPORollovers
    typealias FecthFundsIPODataCompletionHandler = (_ fundsIPOData: [FundIPORolloverDataModels]?,_ error: Error?) -> ()
    func fetchFundsIPOData(nameFund: String,  completionHandler: @escaping FecthFundsIPODataCompletionHandler) {
        
        AF.request("https://www.fame.in.th/FAMEMvc/api/DashUnAuthor/\(nameFund)", method:.post,encoding:    JSONEncoding.default).response { response in
            
            if response.error != nil {
                completionHandler(nil, response.error)
                return
            }
            
            if let data = response.data {
                do {
                    let iPOModelData = try JSONDecoder().decode([FundIPORolloverDataModels].self, from: data)
//                    print("iPOModelData>>", iPOModelData)
                    completionHandler(iPOModelData, nil)
                    
                } catch let error {
                    completionHandler(nil, error)
               
                }
            }
        }
    }
    
    func fetchFundsIPODatas(  completionHandler: @escaping FecthFundsIPODataCompletionHandler) {
        let router = Funds.asURLRequest(Funds.get)
        AF.request(router()).responseData { (response) in
            print(response.value)
            print(response.data ?? "")
            switch response.result {
            case .success:
                print(response.data ?? "")

            case .failure:
                print(response.error)
            }
        }
    }
}
