//
//  IPORolloverModels.swift
//  DemoIPORollver
//
//  Created by BUSSNQ TH on 22/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum IPORollover
{
  // MARK: Use cases
    struct DisplayIPORollover {
        var ipoShowFlag: String?
        var ipoExpireDate: String?
        var fmname : String?
        var fname : String?
        var fundCat: String?
        var ipoExpireDate2: String?
        var ipoOfferDate2: String?
        var tname: String?
        var fundcode: String?
        var ipoInvestment: Int?
        var ipoReward: String?
        var ipoDate2: String?
        var chnfname: String?
        var fundcaten: String?
        var ipoGroup: String?
        var smpic: String?
        var ipoOfferDate: String?
        var ipoRollOver: String?
        var fcode: String?
        var Langauge: String?
        var lgpic: String?
        var ipoDate: String?
        var ipoDuration: String?
        var ipoDetails : String?
        var fundcatth: String?
        var id: Int?
        var risklevel: Int?
        var scope_id: Int?
        var chnfmname: String?
        var ename: String?
        var fxRisk: String?
    }
  enum Something {
    
    struct Request {
        
    }
    struct Response {
        
        var ipoRolloverData: [IPORolloverModel] = []
    }
    struct ViewModel {
        
        var ipoRolloverData: [IPORolloverModel] = []
    }
  }
}
