//
//  IPORolloverWorker.swift
//  DemoIPORollver
//
//  Created by BUSSNQ TH on 22/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON
protocol IPOFetchType {
   
}
class IPORolloverWorker {
    var fetchIPORollover: [IPORolloverModel] = []
  func doSomeWork() {
    let url = "https://www.fame.in.th/FAMEMvc/api/DashUnAuthor/IPO"
   Alamofire.request(url, method:.post,encoding: JSONEncoding.default).validate(contentType: ["application/json; charset=utf-8"]).responseJSON { (response) ->  Void in
        switch response.result {
        case .success:
            print("Successful")
//            print("Data ", response.value)
            do {
                
                let dataJSON = JSON(response.value ?? "")
                let fundipo = dataJSON[]
//                    print("DataJSON",fundipo)
                let fundipoData = try fundipo.rawData(options: .fragmentsAllowed)//AnalystTalk
                let fundipoModel = try JSONDecoder().decode([IPORolloverModel].self, from: fundipoData)// IPO
//                print(fundipoModel)
                self.fetchIPORollover = fundipoModel
                print("Data>>>", self.fetchIPORollover )
                
            }
            catch let err{
                print("Err", err)
                }
        case let .failure(error):
            print(error)
            }
    }
}
}
