//
//  IPORolloverInteractor.swift
//  DemoIPORollver
//
//  Created by BUSSNQ TH on 22/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IPORolloverBusinessLogic
{
  func doSomething(request: IPORollover.Something.Request)
}

protocol IPORolloverDataStore
{
  //var name: String { get set }
}

class IPORolloverInteractor: IPORolloverBusinessLogic, IPORolloverDataStore
{
  var presenter: IPORolloverPresentationLogic?
  var worker: IPORolloverWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: IPORollover.Something.Request)
  {
    worker = IPORolloverWorker()
    worker?.doSomeWork()
    let requestWorker = worker?.fetchIPORollover
    let response = IPORollover.Something.Response(ipoRolloverData: requestWorker!)
    presenter?.presentSomething(response: response)
  }
}
