//
//  SaveBuySellPresenter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 16/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SaveBuySellPresentationLogic
{
  func presentFundscode(response: SaveBuySell.FetchFundsDataHistory.Response)
}

class SaveBuySellPresenter: SaveBuySellPresentationLogic
{
  weak var viewController: SaveBuySellDisplayLogic?
  
  // MARK: Do something
  
    func presentFundscode(response: SaveBuySell.FetchFundsDataHistory.Response)
  {
        let viewModel = SaveBuySell.FetchFundsDataHistory.ViewModel(getHistory: response.getHistory)
    viewController?.displayfetchfundscode(viewModel: viewModel)
  }
}
