//
//  SaveBuySellInteractor.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 16/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SaveBuySellBusinessLogic
{
    func doFetchFundsId(request: SaveBuySell.FetchFundsDataHistory.Request)
}

protocol SaveBuySellDataStore
{
    var getHistory: [DataGetHistoryModel]? { get set }

}

class SaveBuySellInteractor: SaveBuySellBusinessLogic, SaveBuySellDataStore
{
    var getHistory: [DataGetHistoryModel]?
  var presenter: SaveBuySellPresentationLogic?
  var worker: SaveBuySellWorker?
  //var name: String = ""
   
  // MARK: Do something
  
    func doFetchFundsId(request: SaveBuySell.FetchFundsDataHistory.Request) {
        let response = SaveBuySell.FetchFundsDataHistory.Response(getHistory: getHistory )
//        print("getHistory", response.getHistory ?? "")
        presenter?.presentFundscode(response: response)
    }
}
