//
//  SaveBuySellViewController.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 16/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SaveBuySellDisplayLogic: class
{
    func displayfetchfundscode(viewModel: SaveBuySell.FetchFundsDataHistory.ViewModel)
}

class SaveBuySellViewController: UIViewController, SaveBuySellDisplayLogic
{
    @IBOutlet weak var tableView: UITableView!
    var  getHistory: [DataGetHistoryModel]?
    var interactor: SaveBuySellBusinessLogic?
    var router: (NSObjectProtocol & SaveBuySellRoutingLogic & SaveBuySellDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SaveBuySellInteractor()
    let presenter = SaveBuySellPresenter()
    let router = SaveBuySellRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doFetchFundsId()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
func doFetchFundsId() {
    let request = SaveBuySell.FetchFundsDataHistory.Request()
    interactor?.doFetchFundsId(request: request)
    
    }
func displayfetchfundscode(viewModel: SaveBuySell.FetchFundsDataHistory.ViewModel) {
     
        self.getHistory = viewModel.getHistory
        self.tableView.reloadData()
    }

}
extension SaveBuySellViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.getHistory?.count ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "SaveBuySellViewCell") as! SaveBuySellViewCell
        cell.dataHistory = self.getHistory?[indexPath.row]
        return cell
    }
    
    
}
