//
//  FundsIPORolloverInteractor.swift
//  QuizFundsIPO
//
//  Created by BUSSNQ TH on 25/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundsIPORolloverBusinessLogic
{
    func setupFetchFundsIPO(request: FundsIPORolloverModels.FetchFromRemoteDataStore.Request)
}

protocol FundsIPORolloverDataStore {
  var fundsIPOData: [FundIPORolloverDataModels]? { get set }
}

class FundsIPORolloverInteractor: FundsIPORolloverBusinessLogic, FundsIPORolloverDataStore {
    var fundsIPOData: [FundIPORolloverDataModels]?
    
  var presenter: FundsIPORolloverPresentationLogic?
  var worker: FundsIPORolloverWorker?
    typealias Models = FundsIPORolloverModels
  //var name: String = ""
  // MARK: Do something
  
    func setupFetchFundsIPO(request: FundsIPORolloverModels.FetchFromRemoteDataStore.Request) {
        let nameFunds = request.nameFunds
        worker = FundsIPORolloverWorker()
        worker?.fetchFundsIPOData(nameFund: nameFunds) { (fundsIPO, error) in
            if error != nil {
                let response = Models.FetchFromRemoteDataStore.Response(fundsIPO: nil, error: error)
                self.presenter?.presentFetchFundsIPO(response: response)
                return
            }
            
            let response = Models.FetchFromRemoteDataStore.Response(fundsIPO: fundsIPO, error: nil)
          
            self.presenter?.presentFetchFundsIPO(response: response)
        }
        
    }
    
}


