//
//  DeleteMenuRouter.swift
//  QuizFundsPhillip
//
//  Created by BUSSNQ TH on 29/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeleteMenuRoutingLogic
{
    func backtoMainPagePreview()
    func backtoPagePreview()
}

protocol DeleteMenuDataPassing
{
  var dataStore: DeleteMenuDataStore? { get }
}

class DeleteMenuRouter: NSObject, DeleteMenuRoutingLogic, DeleteMenuDataPassing
{
  weak var viewController: DeleteMenuViewController?
  var dataStore: DeleteMenuDataStore?
  
  // MARK: Routing
    func backtoMainPagePreview() {
//        let destinationtabbarVC = UITapbar.performSegue(withIdentifier: "tabBar", sender: self
       
        viewController?.view.window?.rootViewController?.dismiss(animated: false, completion: nil)
        
    }
    func backtoPagePreview() {
        viewController?.dismiss(animated: true, completion: nil)
    }
}
