//
//  NavAnalystReportPresenter.swift
//  QuizAnalystReport
//
//  Created by BUSSNQ TH on 26/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NavAnalystReportPresentationLogic
{
  func presentSomething(response: NavAnalystReport.Something.Response)
    func presentWeekly(response: NavAnalystReport.WeeklyData.Response)
    func presentMonthly(response: NavAnalystReport.MonthlyData.Response)
    func presentAnalystTalks(response: NavAnalystReport.AnalystTalk.Response)
}

class NavAnalystReportPresenter: NavAnalystReportPresentationLogic
{
    
    
   
    
  weak var viewController: NavAnalystReportDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NavAnalystReport.Something.Response)
  {
    let viewModel = NavAnalystReport.Something.ViewModel(analystReportData: response.analystReportData)
    viewController?.displaySomething(viewModel: viewModel)
  }
    func presentWeekly(response: NavAnalystReport.WeeklyData.Response) {
        let viewModel = NavAnalystReport.WeeklyData.ViewModel(analystReportWeeklyData: response.analystReportWeeklyData)
        viewController?.displayWeekly(viewModel: viewModel)
    }
    func presentMonthly(response: NavAnalystReport.MonthlyData.Response){
        let viewModel = NavAnalystReport.MonthlyData.ViewModel(analystReportMonthlyData: response.analystReportMonthlyData)
        viewController?.displayMonthly(viewModel: viewModel)
    }
    func presentAnalystTalks(response: NavAnalystReport.AnalystTalk.Response) {
        let viewModel = NavAnalystReport.AnalystTalk.ViewModel(analystTalkData: response.analystTalkData , error: response.error)
        viewController?.displayAnalystTalks(viewModel: viewModel)
    }
}
