//
//  AnalystReportPresenter.swift
//  QuizAnalystReport
//
//  Created by BUSSNQ TH on 26/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AnalystReportPresentationLogic
{
  func presentSomething(response: AnalystReport.FetchAnalystReportDataStore.Response)
}

class AnalystReportPresenter: AnalystReportPresentationLogic
{
  weak var viewController: AnalystReportDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: AnalystReport.FetchAnalystReportDataStore.Response) {
    let viewModel = AnalystReport.FetchAnalystReportDataStore.ViewModel(analystReportData: response.analystReportData, error: response.error)
    viewController?.displayAnalystReport(viewModel: viewModel)
  }
}
