//
//  AnalystReportInteractor.swift
//  QuizAnalystReport
//
//  Created by BUSSNQ TH on 26/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AnalystReportBusinessLogic {
  func doSomething(request: AnalystReport.FetchAnalystReportDataStore.Request)
}

protocol AnalystReportDataStore {
  var analystReport: [AnalystReportModel]? { get set }
}

class AnalystReportInteractor: AnalystReportBusinessLogic, AnalystReportDataStore
{
    var analystReport: [AnalystReportModel]?
    
  var presenter: AnalystReportPresentationLogic?
  var worker: AnalystReportWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AnalystReport.FetchAnalystReportDataStore.Request) {
    let nameFunds = request.nameAnalystReport
    worker = AnalystReportWorker()
    worker?.doFetchAnalystReport(nameFunds: nameFunds) { (analystReport ,error )in
        if error != nil {
        let response = AnalystReport.FetchAnalystReportDataStore.Response(analystReportData: nil, error: error)
        self.presenter?.presentSomething(response: response)
        return
    }
    
    let response = AnalystReport.FetchAnalystReportDataStore.Response(analystReportData: analystReport, error: nil)
    self.presenter?.presentSomething(response: response)
}

}


}
