//
//  AnalystReportRouter.swift
//  QuizAnalystReport
//
//  Created by BUSSNQ TH on 26/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AnalystReportRoutingLogic
{
    func goToNavAnalystReport(analystReportData: AnalystReportModel)
}

protocol AnalystReportDataPassing
{
  var dataStore: AnalystReportDataStore? { get }
}

class AnalystReportRouter: NSObject, AnalystReportRoutingLogic, AnalystReportDataPassing
{
    func goToNavAnalystReport(analystReportData: AnalystReportModel) {
        let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "NavAnalystReportViewController") as! NavAnalystReportViewController
             var destinationDS = destinationVC.router!.dataStore!
             destinationDS.analystReport = analystReportData
             viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
//    func goToCakePreview(cakeData: CakeModel) {
//         let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SWSCakePreviewViewController") as! SWSCakePreviewViewController
//         var destinationDS = destinationVC.router!.dataStore!
//         destinationDS.cakeData = cakeData
//         viewController?.navigationController?.pushViewController(destinationVC, animated: true)
//    }
  weak var viewController: AnalystReportViewController?
  var dataStore: AnalystReportDataStore?
  
  // MARK: Routing
  

}
